### ISSUE TITLE
install instructions?

### ISSUE THREAD

**Issue by alsoeric** [kingToolbox/DIGEdit#1]
I downloaded the zip file and unpacked it. Running the executable by itself reported failures to find the DLLs in the same directory. How should I install and run it?

**Comment by kingToolbox** [comment]
Sorry, it was my fault, I forgot two dll. The package has been updated, please  download again. If it still report miss VCRUNTIME140.dll, please install [vc_redist.x86](https://aka.ms/vs/16/release/vc_redist.x86.exe)
